import tkinter as tk
from tkinter import ttk
from CONSTANT.index import *
from app.main.other_components.record_base import RecordBase, CLabel
from error import ErrorModal
from app.main.order_components.show_sales_order_logs import ShowSalesOrderLogs
from app.main.external_files.create_invoice import GenerateInvoice



# Sub Category Single Record Display
class RecordSalesOrder(tk.Toplevel, RecordBase):
    def __init__(self, container, mysql, user, sales_order_id, *args, **kwargs):
        
        # Inheriting tk.Toplevel Class
        super().__init__(container, *args, **kwargs)
        self.grab_set()
        self.state('zoomed') # Open App fullscreen in maximize window  
        self.product_list = list()
        # Inheriting RecordBase Class
        # Class.contructor(instance_or_object) is right syntax
        RecordBase.__init__(self, mysql, user, POPUP_TITLE="Sales Order / Customer's Invoice Details", button_2_text=None) # Class.contructor(instance or object) is right syntax
        
        # necessary instance variable for particular class
        self.sales_order_id = sales_order_id

        # Render Contents inside Canvas 
        self.renderLabels(record_table_name = self.POPUP_TITLE)
        
        # Fetch and show data
        self.fetchDataAndRender()
        
        
        
    def renderLabels(self, record_table_name):
        # Heading Label
        heading_label = ttk.Label(self.frame, text=record_table_name, anchor="center", style="PageHeadingLabel.TLabel")
        heading_label.grid(row=0, column=0, columnspan=2, sticky="ew")
        
        # Contents to Display in Canvas
        lb_1 = CLabel(self.frame, text="Sales Order Id: ", font=SINGLE_RECORD_DISPLAY_LABEL_TITLE_FONT)
        lb_1.grid(row=1, column=0, sticky="nsew")
        
        self.order_id_label = CLabel(self.frame, font=SINGLE_RECORD_DISPLAY_LABEL_VALUE_FONT)
        self.order_id_label.grid(row=1, column=1, sticky="nsew")

        lb_1 = CLabel(self.frame, text="Customer's Name: ", font=SINGLE_RECORD_DISPLAY_LABEL_TITLE_FONT)
        lb_1.grid(row=2, column=0, sticky="nsew")
        
        self.c_name_label = CLabel(self.frame, font=SINGLE_RECORD_DISPLAY_LABEL_VALUE_FONT)
        self.c_name_label.grid(row=2, column=1, sticky="nsew")

        lb_1 = CLabel(self.frame, text="Customer's Mobile: ", font=SINGLE_RECORD_DISPLAY_LABEL_TITLE_FONT)
        lb_1.grid(row=3, column=0, sticky="nsew")
        
        self.c_mobile_label = CLabel(self.frame, font=SINGLE_RECORD_DISPLAY_LABEL_VALUE_FONT)
        self.c_mobile_label.grid(row=3, column=1, sticky="nsew")
        
        lb_1 = CLabel(self.frame, text="Customer's E-Mail: ", font=SINGLE_RECORD_DISPLAY_LABEL_TITLE_FONT)
        lb_1.grid(row=4, column=0, sticky="nsew")
        
        self.c_email_label = CLabel(self.frame, font=SINGLE_RECORD_DISPLAY_LABEL_VALUE_FONT)
        self.c_email_label.grid(row=4, column=1, sticky="nsew")

        lb_1 = CLabel(self.frame, text="Status: ", font=SINGLE_RECORD_DISPLAY_LABEL_TITLE_FONT)
        lb_1.grid(row=5, column=0, sticky="nsew")
        
        self.status_label = CLabel(self.frame, font=SINGLE_RECORD_DISPLAY_LABEL_VALUE_FONT)
        self.status_label.grid(row=5, column=1, sticky="nsew")

        lb_1 = CLabel(self.frame, text="Payment Mode: ", font=SINGLE_RECORD_DISPLAY_LABEL_TITLE_FONT)
        lb_1.grid(row=6, column=0, sticky="nsew")
        
        self.payment_mode_label = CLabel(self.frame, font=SINGLE_RECORD_DISPLAY_LABEL_VALUE_FONT)
        self.payment_mode_label.grid(row=6, column=1, sticky="nsew")

        lb_1 = CLabel(self.frame, text="Generated By (username): ", font=SINGLE_RECORD_DISPLAY_LABEL_TITLE_FONT)
        lb_1.grid(row=7, column=0, sticky="nsew")
        
        self.username_label = CLabel(self.frame, font=SINGLE_RECORD_DISPLAY_LABEL_VALUE_FONT)
        self.username_label.grid(row=7, column=1, sticky="nsew")

        lb_1 = CLabel(self.frame, text="User Id: ", font=SINGLE_RECORD_DISPLAY_LABEL_TITLE_FONT)
        lb_1.grid(row=8, column=0, sticky="nsew")
        
        self.user_id_label = CLabel(self.frame, font=SINGLE_RECORD_DISPLAY_LABEL_VALUE_FONT)
        self.user_id_label.grid(row=8, column=1, sticky="nsew")

        lb_1 = CLabel(self.frame, text="Created At: ", font=SINGLE_RECORD_DISPLAY_LABEL_TITLE_FONT)
        lb_1.grid(row=9, column=0, sticky="nsew")
        
        self.created_at_label = CLabel(self.frame, font=SINGLE_RECORD_DISPLAY_LABEL_VALUE_FONT)
        self.created_at_label.grid(row=9, column=1, sticky="nsew")

        self.p_frame = ttk.Frame(self.frame)
        self.p_frame.grid(row=10, column=0, columnspan=2, sticky="ew")

        self.show_logs_button = ttk.Button(
            self.frame,
            text="Show Sales Order Logs",
            command= lambda: ShowSalesOrderLogs(self, self.mysql, self.current_user, self.sales_order_id),
            style="SingleRecordLinkButton.TButton"
            )
        self.show_logs_button.grid(row=11, column=0, columnspan=2, sticky="ew")

        self.print_button = ttk.Button(
            self.frame,
            text="Print",
            command= lambda: GenerateInvoice(sales_order_id=self.sales_order_id),
            style="SingleRecordLinkButton.TButton"
            )
        self.print_button.grid(row=12, column=0, columnspan=2, sticky="ew")



    # Fetch Data from Database of Record and display it    
    def fetchDataAndRender(self):
        try:
            # Fetch Purchase Order Details
            data = self.queryFetchSingleSalesOrder(self.sales_order_id)
            # Display Data
            self.order_id_label.configure(text=data[0][SALES_ORDER_ID])
            self.c_name_label.configure(text=data[0][SALES_ORDER_C_NAME])
            self.c_mobile_label.configure(text=data[0][SALES_ORDER_C_MOBILE])
            self.c_email_label.configure(text=data[0][SALES_ORDER_C_EMAIL])
            self.status_label.configure(text=data[0][SALES_ORDER_STATUS])
            self.payment_mode_label.configure(text=data[0][SALES_ORDER_PAYMENT_MODE])
            self.username_label.configure(text=data[0][USERNAME])
            self.user_id_label.configure(text=data[0][SALES_ORDER_FOREIGNKEY_USER_ID])
            self.created_at_label.configure(text=data[0][CREATED_AT])

            # Fetch Products in Purchase Order Details
            self.product_list = self.queryFetchAllSalesOrderProduct(self.sales_order_id)

            # Render Products
            self.renderProducts(data[0][SALES_ORDER_TOTAL_PRICE])

        except Exception as error:
            print(f"Develpoment Error (While fetching sales order details): {error}")
            ErrorModal("Something went wrong, please contact the developer.")



    def renderProducts(self, total_bill_amount):
        
        self.p_frame.columnconfigure(0, weight=1)
        self.p_frame.columnconfigure(1, weight=1)
        self.p_frame.columnconfigure(2, weight=1)

        # Headings
        h_lb = ttk.Label(self.p_frame, text="Product details in invoice", anchor="center", style="PageHeadingLabel.TLabel")
        h_lb.grid(row=0, column=0, columnspan=4, sticky="ew")

        heading_rows = 1
        last_row = 0

        # Rendering Products
        for i in range(len(self.product_list)):
            lb_1 = CLabel(self.p_frame, text=f"{self.product_list[i][PRODUCT_NAME]}\n(Product Id = {self.product_list[i][P_O_P_FOREIGNKEY_PRODUCT_ID]})", font=SINGLE_RECORD_DISPLAY_LABEL_TITLE_FONT)
            lb_1.grid(row=i+heading_rows, column=0, columnspan=3, sticky="nsew")
            lb_1 = CLabel(self.p_frame, text=f"Price: {self.formatINR(self.product_list[i][P_O_P_PRODUCT_PRICE])}", font=SINGLE_RECORD_DISPLAY_LABEL_TITLE_FONT)
            lb_1.grid(row=i+heading_rows+1, column=0, sticky="nsew")
            lb_1 = CLabel(self.p_frame, text=f"Quantity: x{self.product_list[i][P_O_P_PRODUCT_QUANTITY]}", font=SINGLE_RECORD_DISPLAY_LABEL_TITLE_FONT)
            lb_1.grid(row=i+heading_rows+1, column=1, sticky="nsew")
            lb_1 = CLabel(self.p_frame, text=f"Total: {self.formatINR(self.product_list[i][P_O_P_PRODUCT_TOTAL_AMOUNT])}", font=SINGLE_RECORD_DISPLAY_LABEL_TITLE_FONT)
            lb_1.grid(row=i+heading_rows+1, column=2, sticky="nsew")

            # Returned and Cancelled Labels
            fr = ttk.Frame(self.p_frame)
            fr.grid(row=i+heading_rows+2, column=0, columnspan=3, sticky="nsew")
            fr.columnconfigure(0, weight=1)
            fr.columnconfigure(1, weight=1)
            lb_1 = CLabel(fr, text=f"Returned Quantity: x {self.product_list[i][RETURNED_QUANTITY]}", font=SINGLE_RECORD_DISPLAY_LABEL_TITLE_FONT)
            lb_1.grid(row=0, column=0, sticky="nsew")
            lb_1 = CLabel(fr, text=f"Cancelled Quantity: x {self.product_list[i][CANCELLED_QUANTITY]}", font=SINGLE_RECORD_DISPLAY_LABEL_TITLE_FONT)
            lb_1.grid(row=0, column=1, sticky="nsew")
            lb_1 = CLabel(fr, text=f"Refunded Amount: {self.formatINR(self.product_list[i][REFUNDED_AMOUNT])}", font=SINGLE_RECORD_DISPLAY_LABEL_TITLE_FONT)
            lb_1.grid(row=i+heading_rows+3, column=0, columnspan=3, sticky="nsew")

            # White separator
            h_lb = ttk.Label(self.p_frame, text=" ", anchor="center", style="EmptyLineLabel.TLabel")
            h_lb.grid(row=i+heading_rows+4, column=0, columnspan=3, sticky="ew")
            heading_rows = heading_rows + 5
            last_row = i+heading_rows+1

        lb_1 = CLabel(self.p_frame, text=f"Total Bill Amount: {self.formatINR(total_bill_amount)}", font=SINGLE_RECORD_DISPLAY_LABEL_TITLE_FONT)
        lb_1.grid(row=last_row+1, column=0, columnspan=3, sticky="nsew")



     # Refreshing the Widget   
    def customReset(self):
        self.fetchDataAndRender()