from CONSTANT.table_constants import  *
from app.main.external_files.export_data_base import ExportDataBase

class ExportPurchaseOrderData(ExportDataBase):
    def __init__(self, getQueryMethod, container=None):
        super().__init__()

        # Setting download locationa and file location in app
        self.setFilePaths(file_name_prefix="purchase_order")
        
        # Creating DataFrame for main purchase order table similar to 2d object
        self.createDataFrame(lambda: getQueryMethod())


        # Getting all the selected purchase order id
        purchase_order_id_tuple = tuple(self.data_frame[PURCHASE_ORDER_ID].values)
        
        # Custom Column Names for Purchase Order
        columns_dictionary_main = {
            PURCHASE_ORDER_ID: "Purchase Order Id",
            PURCHASE_ORDER_FOREIGNKEY_SUPPLIER_ID: "Supplier Id",
            SUPPLIER_NAME: "Supplier Name",
            SUPPLIER_CONTACT_1: "Supplier Contact",
            SUPPLIER_ADDRESS: "Supplier Address",
            SUPPLIER_GSTIN: "Supplier GSTIN",
            SUPPLIER_ORGANIZATION_NAME: "Supplier's Organization Name",
            SUPPLIER_ORGANIZATION_CONTACT_1: "Organization's Contact",
            SUPPLIER_ORGANIZATION_ADDRESS: "Organization Address",
            PURCHASE_ORDER_PAYMENT_MODE: "Payment Mode",
            PURCHASE_ORDER_STATUS: "Order Status",
            PURCHASE_ORDER_TOTAL_PRICE: "Total Bill Amount (INR)",
            PURCHASE_ORDER_PAYMENT_STATUS: "Payment Status",
            PURCHASE_ORDER_DELIVERY_STATUS: "Delivery Status",
            SALES_ORDER_FOREIGNKEY_USER_ID: "Generated By (User Id)",
            USERNAME: "Generated By (Username)",
            CREATED_AT: "Generated At",
        }
        # Give custom column names to the DataFrame of Purchase Order
        self.data_frame = self.data_frame.rename(columns=columns_dictionary_main)

        # Write the data to an Excel file
        self.data_frame.to_excel(self.writer, sheet_name="Purchase Order Details", index=False, na_rep="")
        # Query for get Purchase_ORDER_PRODUCT
        if len(purchase_order_id_tuple) == 1:
            # When only one element in tuple (1,) comma will give error in sql statement
            query_purchase_order_product = f"""SELECT * FROM  `{PURCHASE_ORDER_PRODUCT_TABLE_NAME}` 
            WHERE `{P_O_P_FOREIGNKEY_PURCHASE_ORDER_ID}` IN ({purchase_order_id_tuple[0]});"""
        else:
            query_purchase_order_product = f"""SELECT * FROM  `{PURCHASE_ORDER_PRODUCT_TABLE_NAME}` 
            WHERE `{P_O_P_FOREIGNKEY_PURCHASE_ORDER_ID}` IN {purchase_order_id_tuple};"""

        # Creating DataFrame for main purchase order products table similar to 2d object
        self.createDataFrame(query_str=query_purchase_order_product)

        # Remove first Column
        self.data_frame.pop(P_O_P_ID)
        # Custom Column Names for Purchase Order
        columns_dictionary_sub = {
            P_O_P_ID: "Id",
            P_O_P_FOREIGNKEY_PURCHASE_ORDER_ID: "Purchase Order Id",
            P_O_P_FOREIGNKEY_PRODUCT_ID: "Product Id",
            PRODUCT_NAME: "Product Name",
            P_O_P_PRODUCT_PRICE: "Buying Price",
            P_O_P_PRODUCT_QUANTITY: "Bought quantity",
            P_O_P_PRODUCT_TOTAL_AMOUNT: "Total for product (INR)",
            RETURNED_QUANTITY: "Returned Quantities",
            CANCELLED_QUANTITY: "Cancelled Quantities",
            REFUNDED_AMOUNT: "Amount Refunded",
            CREATED_AT: "Generated At",
        }
        # Give custom column names to the DataFrame of Purchase Order
        self.data_frame = self.data_frame.rename(columns=columns_dictionary_sub)

        # Write the data to an Excel file
        self.data_frame.to_excel(self.writer, sheet_name="Product Details in Orders", index=False, na_rep="")

        # set width and center alignments to all columns
        self.configureExcelSheetsWidthAndAlignment(sheet_names = ["Purchase Order Details", "Product Details in Orders"])

        if type(container) == None.__class__:
            # Moving excel file from app to downloads
            self.moveFileToDownload()
        else:
            # Moving excel file from app to downloads
            self.moveFileToDownload(container)
